// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core_dart/firebase_core_dart.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnxKyn8HN5mQ-s0GboFPPzJQ0p8qb_FMU',
    appId: '1:932879788460:web:a6b8ee0d72ea5f3a883209',
    messagingSenderId: '932879788460',
    projectId: 'flutter-todo-bloc-6ce04',
    authDomain: 'flutter-todo-bloc-6ce04.firebaseapp.com',
    storageBucket: 'flutter-todo-bloc-6ce04.appspot.com',
    measurementId: 'G-DR773GM16H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCorbgwTD21xNCSh3MB8I1PIbC60ZCCdfI',
    appId: '1:932879788460:android:71a649b7ddb84d09883209',
    messagingSenderId: '932879788460',
    projectId: 'flutter-todo-bloc-6ce04',
    storageBucket: 'flutter-todo-bloc-6ce04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB73Y-Aqno9Z3TMaTeJNxNuCOs7hKUcAi0',
    appId: '1:932879788460:ios:69ac7c7ba957e22d883209',
    messagingSenderId: '932879788460',
    projectId: 'flutter-todo-bloc-6ce04',
    storageBucket: 'flutter-todo-bloc-6ce04.appspot.com',
    iosBundleId: 'com.example.blockArch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB73Y-Aqno9Z3TMaTeJNxNuCOs7hKUcAi0',
    appId: '1:932879788460:ios:f91d48bf42d47061883209',
    messagingSenderId: '932879788460',
    projectId: 'flutter-todo-bloc-6ce04',
    storageBucket: 'flutter-todo-bloc-6ce04.appspot.com',
    iosBundleId: 'com.example.blockArch.RunnerTests',
  );
}
